CREATE TABLE "audit_application" (
  "application_id" integer PRIMARY KEY,
  "application_name" varchar,
  "application_desc" varchar,
  "status" varchar,
  "created_date" date,
  "created_by" varchar
);

CREATE TABLE "audit_app_task" (
  "application_id" integer,
  "task_id" integer,
  "task_name" varchar,
  "task_desc" varchar,
  "status" varchar,
  "created_date" date,
  "created_by" varchar,
  PRIMARY KEY ("application_id", "task_id")
);

CREATE TABLE "audit_batch_log" (
  "batch_id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "application_id" integer,
  "batch_start_time" datetime,
  "batch_end_time" datetime,
  "status" varchar,
  "created_date" date,
  "created_by" varchar,
  "last_upd_time" datetime,
  "last_upd_by" varchar,
  PRIMARY KEY ("batch_id", "application_id")
);

CREATE TABLE "audit_batch_control" (
  "batch_id" integer,
  "application_id" integer,
  "task_id" integer,
  "task_start_time" datetime,
  "task_end_time" datetime,
  "status" varchar,
  "source_record_count" integer,
  "target_record_count" integer,
  "created_time" datetime,
  "created_by" varchar,
  PRIMARY KEY ("batch_id", "application_id", "task_id")
);

ALTER TABLE "audit_app_task" ADD FOREIGN KEY ("application_id") REFERENCES "audit_application" ("application_id");

ALTER TABLE "audit_batch_log" ADD FOREIGN KEY ("application_id") REFERENCES "audit_application" ("application_id");

ALTER TABLE "audit_batch_control" ADD FOREIGN KEY ("batch_id", "application_id") REFERENCES "audit_batch_log" ("batch_id", "application_id");

ALTER TABLE "audit_batch_control" ADD FOREIGN KEY ("application_id", "task_id") REFERENCES "audit_app_task" ("application_id", "task_id");
