COPY INTO HCHB.PC_PATIENTS1_CPY
FROM s3://vnsny-das-staging-test/PC_PATIENTS1.csv.gz
CREDENTIALS = (aws_key_id='XXXXXXXXXXXXXXXXXXXXX' aws_secret_key='xxxxxxxxxxxxxxxxxxxxxxxxxxxxx')
FILE_FORMAT = (TYPE=CSV COMPRESSION= GZIP SKIP_HEADER=1 ESCAPE_UNENCLOSED_FIELD=NONE FIELD_DELIMITER= ',' FIELD_OPTIONALLY_ENCLOSED_BY= '"' ESCAPE='\\' TIMESTAMP_FORMAT='YYYY-MM-DD HH24:MI:SS' DATE_FORMAT='YYYY-MM-DD HH:MI:SS' NULL_IF='')
;
