CREATE TABLE ~database~.~schema~.D_DATE
(
    PK_DATE NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    LOAD_DATE_TIMESTAMP TIMESTAMP_TZ(9) NOT NULL,
    DATE_ACTUAL DATE,
    DAY_OF_WEEK_NUM SMALLINT COMMENT '0=Sun 1=Mon 2=Tue 3=Wed 4=Thu 5=Fri 6=Sat',
    DAY_OF_WEEK_NAME VARCHAR(20),
    DAY_OF_WEEK_SHORT_NAME VARCHAR(20),
    DAY_OF_MONTH_NUM SMALLINT,
    DAY_OF_YEAR_NUM SMALLINT,
    WEEK_OF_YEAR_NUM SMALLINT,
    WEEK_OF_MONTH_NUM SMALLINT,
    MONTH_NUM SMALLINT,
    MONTH_NAME VARCHAR(20),
    MONTH_SHORT_NAME VARCHAR(20),
    QUARTER_NUM SMALLINT,
    QUARTER_NAME VARCHAR(20),
    YEAR_NUM SMALLINT,
    IS_WEEKDAY NUMBER(1)
)
;


INSERT INTO ~database~.~schema~.D_DATE
WITH RECURSIVE CALENDAR_DATES AS
(
SELECT
'2000-01-01'::DATE AS CALENDAR_DATE --start date in the date dimension
UNION ALL
SELECT
DATEADD(day, 1, CALENDAR_DATE)
FROM CALENDAR_DATES
WHERE CALENDAR_DATE <= '2050-12-31' --last date in the date dimension
)
SELECT
CURRENT_TIMESTAMP AS LOAD_DATE_TIMESTAMP,
CALENDAR_DATE AS DATE_ACTUAL,
DAYOFWEEK(CALENDAR_DATE) AS DAY_OF_WEEK_NUM,
[
'SUNDAY',
'MONDAY',
'TUESDAY',
'WEDNESDAY',
'THURSDAY',
'FRIDAY',
'SATURDAY'
][DAYOFWEEK(CALENDAR_DATE)]::VARCHAR(20) AS DAY_OF_WEEK_NAME,
UPPER(DAYNAME(CALENDAR_DATE)) AS DAY_OF_WEEK_SHORT_NAME,
DAYOFMONTH(CALENDAR_DATE) AS DAY_OF_MONTH_NUM,
DAYOFYEAR(CALENDAR_DATE) AS DAY_OF_YEAR_NUM,
WEEKOFYEAR(CALENDAR_DATE) AS WEEK_OF_YEAR_NUM,
CEIL(DAY_OF_MONTH_NUM/7) AS WEEK_OF_MONTH_NUM,
MONTH(CALENDAR_DATE) AS MONTH_NUM,
[
'JANUARY',
'FEBRUARY',
'MARCH',
'APRIL',
'MAY',
'JUNE',
'JULY',
'AUGUST',
'SEPTEMBER',
'OCTOBER',
'NOVEMBER',
'DECEMBER'
][MONTH_NUM-1]::VARCHAR(20) AS MONTH_NAME,
SUBSTR(MONTH_NAME,1,3) AS MONTH_SHORT_NAME,
QUARTER(CALENDAR_DATE) AS QUARTER_NUM,
CONCAT('Q',QUARTER_NUM::VARCHAR) AS QUARTER_NAME,
YEAR(CALENDAR_DATE) AS YEAR_NUM,
CASE
 WHEN DAY_OF_WEEK_NUM=0 OR DAY_OF_WEEK_NUM=6 THEN 0
 ELSE 1
END AS IS_WEEKDAY
FROM CALENDAR_DATES
;
